// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVov1K-jmZOly_ruIkuAwAkabu5UWlcOA',
    appId: '1:894209542016:web:88080d93d7ba0dfaeae365',
    messagingSenderId: '894209542016',
    projectId: 'ecommerce-app-fdf09',
    authDomain: 'ecommerce-app-fdf09.firebaseapp.com',
    storageBucket: 'ecommerce-app-fdf09.firebasestorage.app',
    measurementId: 'G-BSNL9JXW1S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCx_6AWEh4F6RLkaNoiQgZf0rJrnSLaPP0',
    appId: '1:894209542016:android:53efadb856f4e1e6eae365',
    messagingSenderId: '894209542016',
    projectId: 'ecommerce-app-fdf09',
    storageBucket: 'ecommerce-app-fdf09.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFzOVMLsxki_Pz79NcOwk-AcM99yabD-8',
    appId: '1:894209542016:ios:6cc1b600abe01098eae365',
    messagingSenderId: '894209542016',
    projectId: 'ecommerce-app-fdf09',
    storageBucket: 'ecommerce-app-fdf09.firebasestorage.app',
    iosClientId: '894209542016-q7blierqcem3vmi9ldaotqcnjpmin17g.apps.googleusercontent.com',
    iosBundleId: 'com.abdulkader.ecommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFzOVMLsxki_Pz79NcOwk-AcM99yabD-8',
    appId: '1:894209542016:ios:74b5cf3e06d8eb2eeae365',
    messagingSenderId: '894209542016',
    projectId: 'ecommerce-app-fdf09',
    storageBucket: 'ecommerce-app-fdf09.firebasestorage.app',
    iosClientId: '894209542016-2l6cgcdsltl7rslnaq05or7o07akhcks.apps.googleusercontent.com',
    iosBundleId: 'com.abdulkader.eCommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCVov1K-jmZOly_ruIkuAwAkabu5UWlcOA',
    appId: '1:894209542016:web:4446bd8ed4340266eae365',
    messagingSenderId: '894209542016',
    projectId: 'ecommerce-app-fdf09',
    authDomain: 'ecommerce-app-fdf09.firebaseapp.com',
    storageBucket: 'ecommerce-app-fdf09.firebasestorage.app',
    measurementId: 'G-Q8CV7GHENK',
  );

}